import { LinkedList } from './linked-list.js';
const list = new LinkedList();
list.append("dog");
list.append("cat");
list.append("parrot");
list.append("hamster");
list.append("snake");
list.append("turtle");
console.log('Initial list:');
console.log(list.toString());
console.log('\nTesting methods:');
console.log('Size:', list.size()); 
console.log('Head:', list.getHead().value); 
console.log('Tail:', list.getTail().value); 
console.log('At index 2:', list.at(2).value); 
console.log('Contains "cat":', list.contains("cat")); 
console.log('Contains "lion":', list.contains("lion")); 
console.log('Find "hamster":', list.find("hamster")); 
console.log('Find "elephant":', list.find("elephant")); 
console.log('\nAfter popping last element:');
list.pop();
console.log(list.toString());
console.log('\nAfter prepending "rabbit":');
list.prepend("rabbit");
console.log(list.toString());
console.log('\nAfter inserting "fish" at index 3:');
list.insertAt("fish", 3);
console.log(list.toString());
console.log('\n The Linked List after removing index 2:');
list.removeAt(2);
console.log(list.toString());